server {
  listen 80;
  server_name _;

  # Importante: el build de Angular queda dentro de /usr/share/nginx/html
  root /usr/share/nginx/html;
  index index.html;

  # Proxy a microservicios dentro de la red docker-compose
  location /api/productos/ {
    proxy_pass http://msproductos:8080/;
    proxy_http_version 1.1;
    proxy_set_header Host $host;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header X-Forwarded-Proto $scheme;
  }

  location /api/pedidos/ {
    proxy_pass http://mspedidos:8081/;
    proxy_http_version 1.1;
    proxy_set_header Host $host;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header X-Forwarded-Proto $scheme;
  }

  # SPA fallback
  location / {
    try_files $uri $uri/ /index.html;
  }
}